<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cron" Version="1.0.3" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="3.1.9" />
    <PackageReference Include="ncrontab" Version="3.3.3" />
    <PackageReference Include="RestSharp" Version="112.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DepilZone.Entidad\DepilZone.Entidad.csproj" />
  </ItemGroup>

</Project>
