<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cron" Version="1.0.3" />
    <PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR" Version="2.0.8" />
    <PackageReference Include="ncrontab" Version="3.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DepilZone.Data\DepilZone.Data.csproj" />
  </ItemGroup>

</Project>
